# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v2ray.com/core/proxy/vless/inbound/config.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v2ray.com.core.common.net import address_pb2 as v2ray_dot_com_dot_core_dot_common_dot_net_dot_address__pb2
from v2ray.com.core.common.protocol import user_pb2 as v2ray_dot_com_dot_core_dot_common_dot_protocol_dot_user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='v2ray.com/core/proxy/vless/inbound/config.proto',
  package='v2ray.core.proxy.vless.inbound',
  syntax='proto3',
  serialized_options=b'\n\"com.v2ray.core.proxy.vless.inboundP\001Z\007inbound\252\002\036V2Ray.Core.Proxy.Vless.Inbound',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/v2ray.com/core/proxy/vless/inbound/config.proto\x12\x1ev2ray.core.proxy.vless.inbound\x1a\'v2ray.com/core/common/net/address.proto\x1a)v2ray.com/core/common/protocol/user.proto\"e\n\x08\x46\x61llback\x12/\n\x04\x61\x64\x64r\x18\x01 \x01(\x0b\x32!.v2ray.core.common.net.IPOrDomain\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x0c\n\x04unix\x18\x03 \x01(\t\x12\x0c\n\x04xver\x18\x04 \x01(\r\"h\n\x0b\x46\x61llback_h2\x12/\n\x04\x61\x64\x64r\x18\x01 \x01(\x0b\x32!.v2ray.core.common.net.IPOrDomain\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\x0c\n\x04unix\x18\x03 \x01(\t\x12\x0c\n\x04xver\x18\x04 \x01(\r\"\xca\x01\n\x06\x43onfig\x12.\n\x04user\x18\x01 \x03(\x0b\x32 .v2ray.core.common.protocol.User\x12\x12\n\ndecryption\x18\x02 \x01(\t\x12:\n\x08\x66\x61llback\x18\x03 \x01(\x0b\x32(.v2ray.core.proxy.vless.inbound.Fallback\x12@\n\x0b\x66\x61llback_h2\x18\x04 \x01(\x0b\x32+.v2ray.core.proxy.vless.inbound.Fallback_h2BP\n\"com.v2ray.core.proxy.vless.inboundP\x01Z\x07inbound\xaa\x02\x1eV2Ray.Core.Proxy.Vless.Inboundb\x06proto3'
  ,
  dependencies=[v2ray_dot_com_dot_core_dot_common_dot_net_dot_address__pb2.DESCRIPTOR,v2ray_dot_com_dot_core_dot_common_dot_protocol_dot_user__pb2.DESCRIPTOR,])




_FALLBACK = _descriptor.Descriptor(
  name='Fallback',
  full_name='v2ray.core.proxy.vless.inbound.Fallback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr', full_name='v2ray.core.proxy.vless.inbound.Fallback.addr', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='v2ray.core.proxy.vless.inbound.Fallback.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unix', full_name='v2ray.core.proxy.vless.inbound.Fallback.unix', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xver', full_name='v2ray.core.proxy.vless.inbound.Fallback.xver', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=268,
)


_FALLBACK_H2 = _descriptor.Descriptor(
  name='Fallback_h2',
  full_name='v2ray.core.proxy.vless.inbound.Fallback_h2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='addr', full_name='v2ray.core.proxy.vless.inbound.Fallback_h2.addr', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='v2ray.core.proxy.vless.inbound.Fallback_h2.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unix', full_name='v2ray.core.proxy.vless.inbound.Fallback_h2.unix', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='xver', full_name='v2ray.core.proxy.vless.inbound.Fallback_h2.xver', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=374,
)


_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='v2ray.core.proxy.vless.inbound.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='v2ray.core.proxy.vless.inbound.Config.user', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='decryption', full_name='v2ray.core.proxy.vless.inbound.Config.decryption', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fallback', full_name='v2ray.core.proxy.vless.inbound.Config.fallback', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fallback_h2', full_name='v2ray.core.proxy.vless.inbound.Config.fallback_h2', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=579,
)

_FALLBACK.fields_by_name['addr'].message_type = v2ray_dot_com_dot_core_dot_common_dot_net_dot_address__pb2._IPORDOMAIN
_FALLBACK_H2.fields_by_name['addr'].message_type = v2ray_dot_com_dot_core_dot_common_dot_net_dot_address__pb2._IPORDOMAIN
_CONFIG.fields_by_name['user'].message_type = v2ray_dot_com_dot_core_dot_common_dot_protocol_dot_user__pb2._USER
_CONFIG.fields_by_name['fallback'].message_type = _FALLBACK
_CONFIG.fields_by_name['fallback_h2'].message_type = _FALLBACK_H2
DESCRIPTOR.message_types_by_name['Fallback'] = _FALLBACK
DESCRIPTOR.message_types_by_name['Fallback_h2'] = _FALLBACK_H2
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Fallback = _reflection.GeneratedProtocolMessageType('Fallback', (_message.Message,), {
  'DESCRIPTOR' : _FALLBACK,
  '__module__' : 'v2ray.com.core.proxy.vless.inbound.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.proxy.vless.inbound.Fallback)
  })
_sym_db.RegisterMessage(Fallback)

Fallback_h2 = _reflection.GeneratedProtocolMessageType('Fallback_h2', (_message.Message,), {
  'DESCRIPTOR' : _FALLBACK_H2,
  '__module__' : 'v2ray.com.core.proxy.vless.inbound.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.proxy.vless.inbound.Fallback_h2)
  })
_sym_db.RegisterMessage(Fallback_h2)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'v2ray.com.core.proxy.vless.inbound.config_pb2'
  # @@protoc_insertion_point(class_scope:v2ray.core.proxy.vless.inbound.Config)
  })
_sym_db.RegisterMessage(Config)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
